// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Operation {
    Generate(GenerationRequest),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GenerationOutcome {
    Generated(GenerationReport),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationRequest {
    pub source_root: SourceRoot,
    pub workspace_root: WorkspaceRoot,
    pub manifest_path: ManifestPath,
    pub generation_mode: GenerationMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourceRoot(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkspaceRoot(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ManifestPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum GenerationMode {
    Write,
    Check,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationReport(GeneratedFiles);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFiles(Vec<GeneratedFile>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    pub output_path: OutputPath,
    pub byte_count: ByteCount,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OutputPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ByteCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Manifest {
    pub output_path: OutputPath,
    pub output_kind: OutputKind,
    pub output_surface: OutputSurface,
    pub frontmatter: Frontmatter,
    pub modules: Modules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputKind {
    Markdown,
    Nota,
    Toml,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputSurface {
    Workspace,
    AgentsSkill,
    ClaudeSkill,
    ClaudeCommand,
    CodexPrompt,
    CodexCommand,
    ClaudeAgent,
    CodexAgent,
    PiAgent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Frontmatter(Vec<FrontmatterEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterEntry {
    pub frontmatter_key: FrontmatterKey,
    pub frontmatter_value: FrontmatterValue,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterKey(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterValue(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModulePath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Modules(Vec<ModulePath>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveOutputs(Vec<ActiveOutput>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActiveOutput {
    Skill(ActiveSkill),
    Role(ActiveRole),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveSkill {
    pub output_identifier: OutputIdentifier,
    pub module_identifier: ModuleIdentifier,
    pub skill_category: SkillCategory,
    pub skill_tier: SkillTier,
    pub skill_description: SkillDescription,
    pub target_surfaces: TargetSurfaces,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveRole {
    pub output_identifier: OutputIdentifier,
    pub module_identifier: ModuleIdentifier,
    pub included_modules: IncludedModules,
    pub role_description: RoleDescription,
    pub role_target_surfaces: RoleTargetSurfaces,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OutputIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct ModuleIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IncludedModules(Vec<ModuleIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDescription(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleTargetSurfaces(Vec<RoleTargetSurface>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RoleTargetSurface {
    ClaudeAgent,
    CodexAgent,
    PiAgent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModuleDependencies(Vec<ModuleDependency>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModuleDependency {
    pub module_identifier: ModuleIdentifier,
    pub module_path: ModulePath,
    pub dependency_modules: DependencyModules,
    pub module_kind: ModuleKind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ModuleKind {
    RuntimeSkill,
    RoleSource,
    RoleComposition,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DependencyModules(Vec<ModuleIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetModuleInsertions(Vec<TargetModuleInsertion>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetModuleInsertion {
    pub module_identifier: ModuleIdentifier,
    pub output_surface: OutputSurface,
    pub included_modules: IncludedModules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedRoleOutputs(Vec<OutputPath>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillRoster {
    pub archive_root: ArchiveRoot,
    pub skill_modules: SkillModules,
    pub entry_points: EntryPoints,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchiveRoot(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillModules(Vec<SkillModule>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillModule {
    pub module_name: ModuleName,
    pub module_path: ModulePath,
    pub module_lifecycle: ModuleLifecycle,
    pub emission_policy: EmissionPolicy,
    pub target_surfaces: TargetSurfaces,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModuleName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ModuleLifecycle {
    Active(SkillMetadata),
    Archived(ArchivePath),
    Deleted,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ArchivePath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillMetadata {
    pub skill_category: SkillCategory,
    pub skill_tier: SkillTier,
    pub skill_description: SkillDescription,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SkillCategory {
    Architecture,
    Craft,
    Programming,
    Workflow,
    Meta,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SkillTier {
    Apex,
    Keystroke,
    Topic,
    Mechanism,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillDescription(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EmissionPolicy {
    FirstClassSkill,
    InternalOnly,
    NoEmission,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetSurfaces(Vec<TargetSurface>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TargetSurface {
    AgentsSkill,
    ClaudeSkill,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryPoints(Vec<EntryPoint>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryPoint {
    pub module_name: ModuleName,
    pub entry_point_extras: EntryPointExtras,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryPointExtras(Vec<EntryPointExtra>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EntryPointExtra {
    pub extra_surface: ExtraSurface,
    pub extra_module_path: ExtraModulePath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ExtraSurface {
    ClaudeCommand,
    CodexPrompt,
    CodexCommand,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraModulePath(Path);

#[rustfmt::skip]
impl SourceRoot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for SourceRoot {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkspaceRoot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for WorkspaceRoot {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ManifestPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ManifestPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GenerationReport {
    pub fn new(payload: GeneratedFiles) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GeneratedFiles {
        &self.0
    }
    pub fn into_payload(self) -> GeneratedFiles {
        self.0
    }
}
#[rustfmt::skip]
impl From<GeneratedFiles> for GenerationReport {
    fn from(payload: GeneratedFiles) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GeneratedFiles {
    pub fn new(payload: Vec<GeneratedFile>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<GeneratedFile> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<GeneratedFile> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<GeneratedFile>> for GeneratedFiles {
    fn from(payload: Vec<GeneratedFile>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for OutputPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ByteCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ByteCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Frontmatter {
    pub fn new(payload: Vec<FrontmatterEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<FrontmatterEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<FrontmatterEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<FrontmatterEntry>> for Frontmatter {
    fn from(payload: Vec<FrontmatterEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FrontmatterKey {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FrontmatterKey {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FrontmatterValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FrontmatterValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModulePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ModulePath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Modules {
    pub fn new(payload: Vec<ModulePath>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModulePath> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModulePath> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModulePath>> for Modules {
    fn from(payload: Vec<ModulePath>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActiveOutputs {
    pub fn new(payload: Vec<ActiveOutput>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ActiveOutput> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ActiveOutput> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ActiveOutput>> for ActiveOutputs {
    fn from(payload: Vec<ActiveOutput>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for OutputIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModuleIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModuleIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IncludedModules {
    pub fn new(payload: Vec<ModuleIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleIdentifier>> for IncludedModules {
    fn from(payload: Vec<ModuleIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleDescription {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RoleDescription {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleTargetSurfaces {
    pub fn new(payload: Vec<RoleTargetSurface>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleTargetSurface> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleTargetSurface> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleTargetSurface>> for RoleTargetSurfaces {
    fn from(payload: Vec<RoleTargetSurface>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModuleDependencies {
    pub fn new(payload: Vec<ModuleDependency>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleDependency> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleDependency> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleDependency>> for ModuleDependencies {
    fn from(payload: Vec<ModuleDependency>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DependencyModules {
    pub fn new(payload: Vec<ModuleIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleIdentifier>> for DependencyModules {
    fn from(payload: Vec<ModuleIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TargetModuleInsertions {
    pub fn new(payload: Vec<TargetModuleInsertion>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TargetModuleInsertion> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TargetModuleInsertion> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TargetModuleInsertion>> for TargetModuleInsertions {
    fn from(payload: Vec<TargetModuleInsertion>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GeneratedRoleOutputs {
    pub fn new(payload: Vec<OutputPath>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<OutputPath> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<OutputPath> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<OutputPath>> for GeneratedRoleOutputs {
    fn from(payload: Vec<OutputPath>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArchiveRoot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ArchiveRoot {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SkillModules {
    pub fn new(payload: Vec<SkillModule>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<SkillModule> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<SkillModule> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<SkillModule>> for SkillModules {
    fn from(payload: Vec<SkillModule>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModuleName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModuleName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ArchivePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ArchivePath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SkillDescription {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SkillDescription {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TargetSurfaces {
    pub fn new(payload: Vec<TargetSurface>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TargetSurface> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TargetSurface> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TargetSurface>> for TargetSurfaces {
    fn from(payload: Vec<TargetSurface>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EntryPoints {
    pub fn new(payload: Vec<EntryPoint>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EntryPoint> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EntryPoint> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EntryPoint>> for EntryPoints {
    fn from(payload: Vec<EntryPoint>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EntryPointExtras {
    pub fn new(payload: Vec<EntryPointExtra>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EntryPointExtra> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EntryPointExtra> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EntryPointExtra>> for EntryPointExtras {
    fn from(payload: Vec<EntryPointExtra>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExtraModulePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ExtraModulePath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl std::fmt::Display for SourceRoot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for SourceRoot {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for SourceRoot {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for WorkspaceRoot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for WorkspaceRoot {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for WorkspaceRoot {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ManifestPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ManifestPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ManifestPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for OutputPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for OutputPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for OutputPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ByteCount {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl PartialEq<u64> for ByteCount {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl PartialOrd<u64> for ByteCount {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl std::fmt::Display for FrontmatterKey {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for FrontmatterKey {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for FrontmatterKey {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for FrontmatterValue {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for FrontmatterValue {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for FrontmatterValue {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModulePath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModulePath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModulePath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for OutputIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for OutputIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for OutputIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModuleIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModuleIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModuleIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for RoleDescription {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for RoleDescription {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for RoleDescription {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ArchiveRoot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ArchiveRoot {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ArchiveRoot {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModuleName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModuleName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModuleName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ArchivePath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ArchivePath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ArchivePath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for SkillDescription {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for SkillDescription {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for SkillDescription {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ExtraModulePath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ExtraModulePath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ExtraModulePath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl Operation {
    pub fn generate(payload: GenerationRequest) -> Self {
        Self::Generate(payload)
    }
}

#[rustfmt::skip]
impl GenerationOutcome {
    pub fn generated(payload: GeneratedFiles) -> Self {
        Self::Generated(GenerationReport::new(payload))
    }
}

#[rustfmt::skip]
impl ActiveOutput {
    pub fn skill(payload: ActiveSkill) -> Self {
        Self::Skill(payload)
    }
    pub fn role(payload: ActiveRole) -> Self {
        Self::Role(payload)
    }
}

#[rustfmt::skip]
impl ModuleLifecycle {
    pub fn active(payload: SkillMetadata) -> Self {
        Self::Active(payload)
    }
    pub fn archived(payload: Path) -> Self {
        Self::Archived(ArchivePath::new(payload))
    }
}

#[rustfmt::skip]
impl From<GenerationRequest> for Operation {
    fn from(payload: GenerationRequest) -> Self {
        Self::Generate(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationReport> for GenerationOutcome {
    fn from(payload: GenerationReport) -> Self {
        Self::Generated(payload)
    }
}

#[rustfmt::skip]
impl From<ActiveSkill> for ActiveOutput {
    fn from(payload: ActiveSkill) -> Self {
        Self::Skill(payload)
    }
}

#[rustfmt::skip]
impl From<ActiveRole> for ActiveOutput {
    fn from(payload: ActiveRole) -> Self {
        Self::Role(payload)
    }
}

#[rustfmt::skip]
impl From<SkillMetadata> for ModuleLifecycle {
    fn from(payload: SkillMetadata) -> Self {
        Self::Active(payload)
    }
}

#[rustfmt::skip]
impl From<ArchivePath> for ModuleLifecycle {
    fn from(payload: ArchivePath) -> Self {
        Self::Archived(payload)
    }
}
